### ISSUE TITLE
Datagram read() functions has changed but not the calls to that function

### ISSUE THREAD

**Issue by tgoettler** [RangeNetworks/openbts#20]
Hello,

when trying to compile the newest version, an error occurs in the file SIP2Interface.cpp.
Here the call to the function read() has only one argument, while the definition of the function has two arguments.

There are many more calls to this function and i am not sure if they are correct.

Bye

**Comment by iedemam** [comment]
Did you also update your submodules?

```
cd openbts-checkout-directory
git submodule update
```

The outer projects have been updated to reference an older version of commonlibs until the best way forward can be determined.

**Comment by tgoettler** [comment]
Hello,

that helped, thank you.
I first used the "build.sh" you provide in the "dev" directory, to automatically build the tool. With this script it did not work.

Bye

**Comment by iedemam** [comment]
Glad it's working. BTW: you can use the dev tool's `pull.sh` script to update all projects and submodules. I just double checked to make sure it handled submodules as well.

Thanks again for the report.
